name: Test Case Generator
description: Generate test cases for the project using the new package structure

on:
  workflow_dispatch:

jobs:
  generate-test-cases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Output Directory
      run: mkdir -p output

    - name: Run Test Case Generator
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        python main.py

    - name: Upload Generated Test Cases
      uses: actions/upload-artifact@v4
      with:
        name: test-case-results
        path: output/

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: test-case-logs
        path: logs/