name: Test Case Generator
description: Generate test cases for the project using main.py
on:
  workflow_call:
    inputs:
      test_case_file:
        required: true
        type: string
        description: The path to the test case file to be generated.
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-test-cases:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Setup Project
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 2: Run main.py with default values
    - name: Run Test Case Generator
      run: |
        python main.py

    # Step 3: Store Results as Artifact
    - name: Upload Results - Generated Test Cases List 
      uses: actions/upload-artifact@v3
      with:
        name: test-case-results
        path: output/